BaseUrl= "http://syui.github.io/hugo-theme-air/"
LanguageCode= "es-ES"
Title= "Hugo Theme Air"
paginate = 3
DisqusShortname = ""
Copyright = "All rights reserved - 2018"
canonifyurls = true

[author]
  name = "Joanh"

[params]
  description = "Ejemplo de sitio estático"
  cover = "images/screen.png"
  author = "Joanh"
  authorlocation = "Madrid, Spain"
  authorwebsite = ""
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "joanh"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
